- Social:
    - Github:
        icon: github-dark.png
        href: https://github.com/pibulus
    - Reddit:
        icon: reddit.png
        href: https://reddit.com

- Chill_Vibes:
    - Groove Salad (SomaFM):
        icon: music.png
        href: https://somafm.com/player/#/now-playing/groovesalad
