title: PIBULUS_OS
theme: dark
color: slate

background:
  image: https://images.unsplash.com/photo-1550745165-9bc0b252726f
  opacity: 20

layout:
  Media:
    style: row
    columns: 4
  Social:
    style: row
    columns: 3
  Tools:
    style: row
    columns: 3
  Fun:
    style: row
    columns: 2
  Photos:
    style: row
    columns: 1
  Offline (start manually):
    style: row
    columns: 4

headerStyle: clean
cardStyle: glass

showSearch: true
search:
  provider: duckduckgo
  target: _blank

providers:
  docker:
    mode: socket
    socket: /var/run/docker.sock
