- datetime:
    format:
      timeStyle: short
- resources:
    cpu: true
    memory: true
    disk: /media/pibulus/passport
- greeting:
    text: "Welcome back!."
    image: "https://quickcat.club/logo.png" # Point this to your new logo!
