(function() {
    if (window.__rommUiCleanup) return;
    window.__rommUiCleanup = true;

    window.EJS_paths = Object.assign({}, window.EJS_paths || {}, {
        "emulator.min.css": "/assets/emulatorjs/data/emulator.css?rev=20260509a",
        "emulator.css": "/assets/emulatorjs/data/emulator.css?rev=20260509a"
    });

    function patchViewportFit() {
        var viewport = document.querySelector('meta[name="viewport"]');
        if (viewport) {
            if (viewport.content.indexOf("viewport-fit") < 0) {
                viewport.content += ",viewport-fit=cover";
            }
            return;
        }

        var meta = document.createElement("meta");
        meta.name = "viewport";
        meta.content = "width=device-width,initial-scale=1,viewport-fit=cover";
        document.head.appendChild(meta);
    }

    var hiddenTabs = {
        manual: 1,
        "game data": 1,
        gamedata: 1,
        "save data": 1,
        "how long to beat": 1,
        timetobeat: 1,
        "additional content": 1,
        additionalcontent: 1,
        "related games": 1,
        "related content": 1,
        relatedgames: 1
    };

    var hiddenLabels = {
        file: 1,
        files: 1,
        info: 1,
        tags: 1,
        "switch version": 1,
        regions: 1,
        languages: 1,
        genres: 1,
        franchises: 1,
        collections: 1,
        companies: 1,
        players: 1,
        "player count": 1,
        "age rating": 1
    };

    var platformHints = [
        "arcade",
        "game boy",
        "game boy advance",
        "nintendo 64",
        "nintendo entertainment",
        "playstation",
        "scummvm",
        "sega mega",
        "sega genesis",
        "super nintendo",
        "turbografx"
    ];

    function normalize(text) {
        text = (text || "").replace(/\s+/g, " ").trim().toLowerCase();
        if (text.slice(-1) === ":") text = text.slice(0, -1);
        return text;
    }

    function hideNode(node, reason) {
        if (!node) return;
        node.style.setProperty("display", "none", "important");
        if (reason) node.setAttribute("data-quickcat-hidden", reason);
    }

    function platformCardShell(node) {
        if (!node) return null;
        return node.closest(".v-slide-group-item,[class*='v-slide-group-item'],.v-col,[class*='v-col'],li") ||
            node.closest(".v-card,a") ||
            node;
    }

    function isHiddenHref(href, prefix) {
        return href === prefix || href.indexOf(prefix + "/") === 0;
    }

    function seedEmulatorDefaults() {
        try {
            var arcadeCore = localStorage.getItem("player:arcade:core");
            if (!arcadeCore || arcadeCore === "mame2003" || arcadeCore === "mame2003_plus") {
                localStorage.setItem("player:arcade:core", "fbneo");
            }
        } catch (error) {}
    }

    function hideNdsCards() {
        if (window.innerWidth > 960) return;

        document.querySelectorAll("a").forEach(function(anchor) {
            var href = anchor.getAttribute("href") || "";
            if (isHiddenHref(href, "/p/15") || isHiddenHref(href, "/platform/nds")) {
                hideNode(platformCardShell(anchor), "nds");
            }
        });

        document.querySelectorAll("span,div,h6,p").forEach(function(element) {
            if (element.childElementCount === 0 && element.textContent.trim() === "Nintendo DS") {
                hideNode(platformCardShell(element), "nds");
            }
        });
    }

    function elementText(node) {
        return normalize(node && node.textContent);
    }

    function platformSectionScore(node) {
        if (!node || !node.querySelectorAll) return 0;

        var text = elementText(node);
        if (!text) return 0;

        var score = text.indexOf("platforms") >= 0 ? 1 : 0;
        platformHints.forEach(function(hint) {
            if (text.indexOf(hint) >= 0) score += 1;
        });

        score += Math.min(node.querySelectorAll("a[href^='/p/'],a[href^='/platform/']").length, 4);

        if (
            text.indexOf("recently added") >= 0 &&
            text.indexOf("continue playing") >= 0 &&
            text.indexOf("autogenerated collections") >= 0
        ) {
            score -= 20;
        }

        return score;
    }

    function homeRoot() {
        return document.querySelector("main .v-container") ||
            document.querySelector(".v-main .v-container") ||
            document.querySelector("main") ||
            document.querySelector(".v-main") ||
            document.body;
    }

    function findPlatformSection(root) {
        var best = null;
        var bestScore = 0;
        var selector = ".v-card,.v-sheet,section,.v-container > div,.v-row,[class*='section'],[class*='Section']";

        root.querySelectorAll(selector).forEach(function(node) {
            var score = platformSectionScore(node);
            if (score < 4) return;
            if (!best || score > bestScore || (score === bestScore && best.contains(node))) {
                best = node;
                bestScore = score;
            }
        });

        return best;
    }

    function topChildWithin(node, root) {
        var current = node;
        while (current && current.parentElement && current.parentElement !== root && current.parentElement !== document.body) {
            current = current.parentElement;
        }
        return current && current.parentElement === root ? current : null;
    }

    function findStatsStrip(root, platformSection) {
        return Array.from(root.children).find(function(child) {
            if (child === platformSection) return false;
            var text = elementText(child);
            return text.indexOf("size on disk") >= 0 && text.indexOf("games") >= 0 && text.indexOf("saves") >= 0;
        });
    }

    function promotePlatformsSection() {
        var path = location.pathname.replace(/\/+$/, "") || "/";
        if (path !== "/") return;

        var root = homeRoot();
        var section = findPlatformSection(root);
        if (!section) return;

        var topSection = topChildWithin(section, root);
        if (!topSection) return;

        section.setAttribute("data-quickcat-platforms-section", "true");
        topSection.setAttribute("data-quickcat-platforms-section", "true");

        var statsStrip = findStatsStrip(root, topSection);
        var target = statsStrip ? statsStrip.nextSibling : root.firstChild;
        if (target && target !== topSection && topSection.previousSibling !== statsStrip) {
            root.insertBefore(topSection, target);
        }
    }

    function hideRommNoise() {
        var path = location.pathname;
        if (!path.startsWith("/rom/") || path.endsWith("/ejs") || path.endsWith("/ejs/")) return;

        document.querySelectorAll(".v-tab,[role=tab],button,a").forEach(function(element) {
            var label = normalize(element.textContent);
            if (hiddenTabs[label]) {
                hideNode(element.closest(".v-slide-group-item,.v-btn,.v-tab,button,a") || element);
            }
        });

        document.querySelectorAll(".text-right.text-medium-emphasis.text-caption.font-italic").forEach(hideNode);
        document.querySelectorAll(".text-caption,.text-overline,.v-list-item-title,dt,th,strong,b,h6,p,span,div").forEach(function(element) {
            if (element.childElementCount > 2) return;
            var label = normalize(element.textContent);
            if (!hiddenLabels[label]) return;
            hideNode(element.closest(".v-list-item,.v-row,.v-col,.d-flex,tr") || element);
        });

        var activeHiddenTab = document.querySelector(".v-tab--selected,.v-btn--active,[role=tab][aria-selected=true]");
        if (activeHiddenTab && hiddenTabs[normalize(activeHiddenTab.textContent)]) {
            var firstVisibleTab = Array.from(document.querySelectorAll(".v-tab,[role=tab]")).find(function(element) {
                return hiddenTabs[normalize(element.textContent)] !== 1 && element.offsetParent !== null;
            });
            if (firstVisibleTab && typeof firstVisibleTab.click === "function") firstVisibleTab.click();
        }
    }

    function run() {
        seedEmulatorDefaults();
        patchViewportFit();
        promotePlatformsSection();
        hideNdsCards();
        hideRommNoise();
    }

    seedEmulatorDefaults();

    document.addEventListener("DOMContentLoaded", function() {
        run();
        new MutationObserver(run).observe(document.body, { childList: true, subtree: true });
    });
})();
