- Connect:
    - GitHub:
        - icon: si-github-#ffffff
          href: https://github.com/pibulus
    - SomaFM Radio:
        - icon: si-musicbrainz-#ff00ff
          href: https://somafm.com/player/#/now-playing/groovesalad
