- Media_Station:
    - The Cinema:
        icon: jellyfin.png
        href: http://pibulus.local:8096
        description: MOVIES & SHOWS (Use 'Guest' to enter)

    - GrooveFM Radio:
        icon: navidrome.png
        href: http://pibulus.local:4533
        description: HI-FI AUDIO STREAM

    - KPAB-TV:
        icon: stremio.png
        href: http://pibulus.local:8000
        description: 24/7 PIRATE BROADCAST

    - Library:
        icon: kavita.png
        href: http://pibulus.local:5000
        description: BOOKS & ARCHIVES

- Community:
    - File Drop:
        icon: filebrowser.png
        href: http://pibulus.local:8080
        description: UPLOAD YOUR MEDIA HERE

- Labs:
    - Stargram:
        icon: code.png
        href: http://pibulus.local:8090/stargram
        description: HOROSCOPE APP v1.0
