title: QUICKCAT.CLUB
theme: dark
color: slate

background:
  image: https://images.unsplash.com/photo-1550745165-9bc0b252726f
  opacity: 30

layout:
  Watch:
    style: row
    columns: 1
  Listen:
    style: row
    columns: 1
  Read:
    style: row
    columns: 1
  Play:
    style: row
    columns: 2
  Share:
    style: row
    columns: 1
  Lab:
    style: row
    columns: 1

headerStyle: clean
cardStyle: glass

showSearch: false
