services:
  web:
    cpu_shares: 2048
    mem_reservation: 512m
    volumes:
      - /media/pibulus/passport/Music:/var/azuracast/stations/kpab.fm/media/My_Library:ro
      - /media/pibulus/passport/Soulseek:/var/azuracast/stations/kpab.fm/media/Soulseek_New:ro
      - /media/pibulus/passport/Soulseek Organized:/var/azuracast/stations/kpab.fm/media/Soulseek_Organized:ro
      - ./fix-gosu.sh:/fix-gosu.sh:ro
      - ./patches/backend/src/Radio/Frontend/Icecast.php:/var/azuracast/www/backend/src/Radio/Frontend/Icecast.php:ro
    entrypoint: ['tini', '--', '/fix-gosu.sh']
    command: []
