name: admin

services:
  homepage-admin:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage_admin
    ports:
      - "8081:3000"
    volumes:
      - /home/pibulus/pibulus-os/config/homepage-admin:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  terminal:
    image: tsl0922/ttyd:latest
    container_name: web_terminal
    ports:
      - "7682:7681"
    environment:
      - TTYD_OPTS="-c user:Church0fTheSubgeniu5!" # Username 'user', Password 'Church0fTheSubgeniu5!'
    volumes:
      - /home/pibulus:/home/pibulus
    command: ttyd -W bash -c "~/pibulus-os/launcher.sh"
    restart: always
