name: social

services:
  irc:
    image: thelounge/thelounge:latest
    container_name: irc
    restart: always
    volumes:
      - /home/pibulus/.config/thelounge:/var/opt/thelounge
    ports:
      - "9000:9000"

  memos:
    image: ghcr.io/usememos/memos:latest
    environment:
      - MEMOS_PUBLIC=true
      - MEMOS_BASE_URL=/memos/
    container_name: memos
    restart: unless-stopped
    volumes:
      - /home/pibulus/.config/memos:/var/opt/memos
    ports:
      - "5230:5230"
    deploy:
      resources:
        limits:
          memory: 128M
