name: social

services:
  irc:
    image: thelounge/thelounge:latest
    container_name: irc
    restart: always
    volumes:
      - /home/pibulus/.config/thelounge:/var/opt/thelounge
    ports:
      - "9000:9000"
